CREATE INDEX "idx_operations_type" ON "operations" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_operations_status" ON "operations" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_inventory_receipts_purchase_request_id" ON "inventory_receipts" USING btree ("purchase_request_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_receipts_posted_by" ON "inventory_receipts" USING btree ("posted_by");--> statement-breakpoint
CREATE INDEX "idx_inventory_issues_requested_by" ON "inventory_issues" USING btree ("requested_by");--> statement-breakpoint
CREATE INDEX "idx_inventory_issues_posted_by" ON "inventory_issues" USING btree ("posted_by");--> statement-breakpoint
CREATE INDEX "idx_inventory_transactions_created_by" ON "inventory_transactions" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_inventory_balances_item_id" ON "inventory_balances" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "idx_qc_requests_confirmed_by" ON "qc_requests" USING btree ("confirmed_by");--> statement-breakpoint
CREATE INDEX "idx_qc_requests_resolved_by" ON "qc_requests" USING btree ("resolved_by");--> statement-breakpoint
CREATE INDEX "idx_qc_inspections_aql_plan_id" ON "qc_inspections" USING btree ("aql_plan_id");--> statement-breakpoint
CREATE INDEX "idx_qc_inspections_qc_department_id" ON "qc_inspections" USING btree ("qc_department_id");--> statement-breakpoint
CREATE INDEX "idx_outsourcing_orders_posted_by" ON "outsourcing_orders" USING btree ("posted_by");--> statement-breakpoint
CREATE INDEX "idx_production_orders_approved_by" ON "production_orders" USING btree ("approved_by");--> statement-breakpoint
CREATE INDEX "idx_production_orders_created_by" ON "production_orders" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_production_order_logs_performed_by" ON "production_order_logs" USING btree ("performed_by");--> statement-breakpoint
CREATE INDEX "idx_production_jobs_started_by" ON "production_jobs" USING btree ("started_by");--> statement-breakpoint
CREATE INDEX "idx_production_job_notes_created_by" ON "production_job_notes" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_requests_sent_by" ON "purchase_requests" USING btree ("sent_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_requests_approved_by" ON "purchase_requests" USING btree ("approved_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_requests_rejected_by" ON "purchase_requests" USING btree ("rejected_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_request_items_cancelled_by" ON "purchase_request_items" USING btree ("cancelled_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_quotations_sent_by" ON "purchase_quotations" USING btree ("sent_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_quotations_approved_by" ON "purchase_quotations" USING btree ("approved_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_quotations_cancelled_by" ON "purchase_quotations" USING btree ("cancelled_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_quotation_item_suppliers_selected_by" ON "purchase_quotation_item_suppliers" USING btree ("selected_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_ordered_by" ON "purchase_orders" USING btree ("ordered_by");--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_cancelled_by" ON "purchase_orders" USING btree ("cancelled_by");--> statement-breakpoint
CREATE INDEX "idx_payment_requests_paid_by" ON "payment_requests" USING btree ("paid_by");--> statement-breakpoint
CREATE INDEX "idx_payment_requests_cancelled_by" ON "payment_requests" USING btree ("cancelled_by");