export enum Role {
  ADMIN = 'ADMIN',
  DIRECTOR = 'DIRECTOR',
  QC = 'QC',
  BUSINESS = 'BUSINESS',
  WAREHOUSE = 'WAREHOUSE',
  PRODUCTION_MANAGER = 'PRODUCTION_MANAGER',
  PROCUREMENT_MANAGER = 'PROCUREMENT_MANAGER',
}
