/**
 * Abstraction over where uploaded file bytes physically live. `key` is the relative storage key
 * generated by the caller (e.g. `2026/07/20/<uuid>.png`), never a full path or URL.
 * Implementations only need to know how to persist/remove bytes for a given key — nothing else in
 * the app (FilesService, the `files` table) knows or cares which driver is behind this interface.
 * Swapping to S3/MinIO later means adding a new implementation and changing `UPLOAD_DRIVER`, no
 * other change. Reading bytes back is `ServeStaticModule`'s job (`app.module.ts`, `upload.dir`),
 * not this interface's — it only needs to write and delete.
 */
export interface StorageProvider {
  save(key: string, buffer: Buffer, mimetype: string): Promise<void>;
  delete(key: string): Promise<void>;
}
