import type { Readable } from 'stream';

/**
 * Abstraction over where uploaded file bytes physically live. `key` is the relative storage key
 * generated by the caller (e.g. `2026/07/20/<uuid>.png`), never a full path or URL. Implementations
 * only need to know how to persist/read/remove bytes for a given key — nothing else in the app
 * (FilesService, the `files` table) knows or cares which driver is behind this interface. Swapping
 * to S3/MinIO later means adding a new implementation and changing `UPLOAD_DRIVER`, no other change.
 *
 * There is deliberately no `getPublicUrl`: no stored file is publicly reachable any more. Bytes are
 * served only through `GET /files/:id/download` behind a signed URL (see `file-url.util.ts`).
 */
export interface StorageProvider {
  save(key: string, buffer: Buffer, mimetype: string): Promise<void>;
  /** Streams rather than buffering — a 10MB cap times N concurrent downloads adds up fast. */
  createReadStream(key: string): Readable;
  delete(key: string): Promise<void>;
}
